In [1]:
import turicreate as tc
import numpy as np

In [2]:
sales = tc.SFrame('./kc_house_data.gl/')
sales

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	int
	floors	str
	waterfront	int
	view	int
	condition	int
	grade	int
	sqft_above	int
	sqft_basement	int
	yr_built	int
	yr_renovated	int
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 21613

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+------------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade | sqft_above |
+-------------+----------+--------+------------+------+-----------+-------+------------+
|    1180.0   |   5650   |   1    |     0      |  0   |     3     |   7   |    1180    |
|    2570.0   |   7242   |   2    |     0      |  0   |     3     |   7   |    2170    |
|    770.0    |  10000   |   1    |     0      |  0   |     3     |   6   |    770     |
|    1960.0   |   5000   |   1    |     0      |  0   |     5     |   7   |    1050    |
|    1680.0   |   8080   |   1    |     0      |  0   |     3     |   8   |    1680    |
|    5420.0   |  101930  |   1    |     0      |  0   |     3     |   11  |    3890    |
|    1715.0   |   6819   |   2    |     0      |  0   |     3     |   7   |    1715    |
|    1060.0   |   9711   |   1    |     0      |  0   |     3     |   7   |    1060    |
|    1780.0   |   7470   |   1    |     0      |  0   |     3     |   7   |    1050    |
|    1890.0   |   6560   |   2    |     0      |  0   |     3     |   7   |    1890    |
+-------------+----------+--------+------------+------+-----------+-------+------------+
+---------------+----------+--------------+---------+-------------+
| sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+---------------+----------+--------------+---------+-------------+
|       0       |   1955   |      0       |  98178  | 47.51123398 |
|      400      |   1951   |     1991     |  98125  | 47.72102274 |
|       0       |   1933   |      0       |  98028  | 47.73792661 |
|      910      |   1965   |      0       |  98136  |   47.52082  |
|       0       |   1987   |      0       |  98074  | 47.61681228 |
|      1530     |   2001   |      0       |  98053  | 47.65611835 |
|       0       |   1995   |      0       |  98003  | 47.30972002 |
|       0       |   1963   |      0       |  98198  | 47.40949984 |
|      730      |   1960   |      0       |  98146  | 47.51229381 |
|       0       |   2003   |      0       |  98038  | 47.36840673 |
+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |
| -122.32704857 |     2238.0    | ... |
| -122.31457273 |     1650.0    | ... |
| -122.33659507 |     1780.0    | ... |
|  -122.0308176 |     2390.0    | ... |
+---------------+---------------+-----+
[21613 rows x 21 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [3]:
train_data, test_data = sales.random_split(.8,seed=0)
input_feature = train_data['sqft_living']
output = train_data['price']

In [4]:
def simple_linear_regression(input_feature, output):
    # quickly assign x and y
    x, y = input_feature.to_numpy(), output.to_numpy()
#     x, y = input_feature, output

    # size of dataset 
    n = np.size(x)
    
    # calculate sums
    sum_x, sum_y = np.sum(x), np.sum(y)
    sum_xx, sum_xy  = np.sum(x**2), np.sum(x*y)
    
    num = (sum_xy) - (1/n)*(sum_x*sum_y)
    denom = (sum_xx) - (1/n)*(sum_x*sum_x)
    
    # calculating regression coefficients
    b_1 = num / denom
    b_0 = np.mean(y) - b_1*np.mean(x)
    
    return b_0,b_1
    
squarefeet_intercept, squarefeet_slope = simple_linear_regression(input_feature, output)
# squarefeet_intercept, squarefeet_slope = simple_linear_regression(np.array([0,1,2,3,4]), np.array([1,3,7,13,21]))

print(squarefeet_intercept, squarefeet_slope)

-47116.07657494 281.9588385676974

In [5]:
def get_regression_predictions(input_feature, intercept, slope):
    # list comprehension, predictions for each value using given intercept and slope
    return [slope*value+intercept for value in input_feature]

# predicted_output = get_regression_predictions(input_feature,squarefeet_intercept,squarefeet_slope)
# print(predicted_output)

In [6]:
answer_1 = get_regression_predictions([2650], squarefeet_intercept, squarefeet_slope)
print(round(answer_1[0],2))

700074.85

In [7]:
def get_residual_sum_of_squares(input_feature, output, intercept, slope):
    # get predictions
    predictions = get_regression_predictions(input_feature, intercept, slope)
    y = output.to_numpy()
    
    # calculate residual
    residual = y - predictions
    
    return np.sum(residual**2)

answer_2 = get_residual_sum_of_squares(input_feature, output, squarefeet_intercept, squarefeet_slope)

In [8]:
print(answer_2)

1201918356321967.5

In [9]:
def inverse_regression_predictions(output, intercept, slope):
    return (output-intercept)/slope

# inv = inverse_regression_predictions(output,squarefeet_intercept,squarefeet_slope)
# print(inv)

In [17]:
answer_3 = inverse_regression_predictions(800000, squarefeet_intercept, squarefeet_slope)
print(round(answer_3,2))

3004.4

In [11]:
input_feature = train_data['bedrooms']
bedroom_intercept, bedroom_slope = simple_linear_regression(input_feature, output)

print(bedroom_intercept, bedroom_slope)

109473.18046928721 127588.95217458403

In [12]:
RSS_bedroom = get_residual_sum_of_squares(input_feature, output, bedroom_intercept, bedroom_slope)
print(RSS_bedroom)

2143244494226579.0

In [18]:
input_feature = test_data['sqft_living']
output = test_data['price']

RSS_sqft = get_residual_sum_of_squares(input_feature, output, squarefeet_intercept, squarefeet_slope)
print(RSS_sqft)

275402936247141.38

In [19]:
input_feature = test_data['bedrooms']
output = test_data['price']

RSS_bedroom = get_residual_sum_of_squares(input_feature, output, bedroom_intercept, bedroom_slope)
print(RSS_bedroom)

493364582868288.1